version: '3.8'

services:
  olx_data_warehouse:
    image: postgres:latest
    container_name: olx_data_warehouse
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - ${POSTGRES_PORT}:5432
    volumes:
      - olx_data_warehouse:/var/lib/postgresql/data
  

volumes:
  olx_data_warehouse:
